DROP TABLE AP_OFICII CASCADE CONSTRAINTS;
DROP TABLE AP_ANGAJATI CASCADE CONSTRAINTS;
DROP TABLE AP_COMPANII CASCADE CONSTRAINTS;
DROP TABLE AP_PRODUSE CASCADE CONSTRAINTS;
DROP TABLE AP_TRANZACTII CASCADE CONSTRAINTS;
DROP SEQUENCE PRODUS_SEQ;

CREATE TABLE AP_OFICII(cod_oficiu VARCHAR2(2) PRIMARY KEY, 
localitatea VARCHAR2(15),
regiunea VARCHAR2(6), 
cod_manager VARCHAR2(3));

CREATE TABLE AP_ANGAJATI (cod_angajat VARCHAR(2) PRIMARY KEY, nume VARCHAR2(15),
prenume VARCHAR2(15),
varsta NUMBER,
functia VARCHAR2(20),
cod_oficiu VARCHAR2(2),
CONSTRAINT fk_cod_of  FOREIGN KEY(cod_oficiu) REFERENCES AP_OFICII(cod_oficiu),data_angajarii date, suma_planificata NUMBER(8,2));

CREATE TABLE AP_COMPANII(cod_companie VARCHAR2(2) PRIMARY KEY, 
compania VARCHAR2(15), 
reprezentant_companie VARCHAR2(3),
datoria NUMBER(*,2),
CONSTRAINT fk_rep  FOREIGN KEY(reprezentant_companie) REFERENCES AP_ANGAJATI(cod_angajat));

CREATE TABLE AP_PRODUSE(cod_produs NUMBER PRIMARY KEY,
descriere VARCHAR2(40),
pret NUMBER(8,2), 
exista VARCHAR2(1) CONSTRAINT ck_ex CHECK(exista='Y' OR exista='N'));

CREATE TABLE AP_TRANZACTII(data_comenzii DATE, 
cod_client VARCHAR(2), 
cod_vanzator VARCHAR2(3),
cod_produs NUMBER,
cantiatea NUMBER,
CONSTRAINT fk_cod_client FOREIGN KEY(cod_client) REFERENCES AP_COMPANII(cod_companie),
CONSTRAINT fk_cod_vanzator FOREIGN KEY(cod_vanzator) REFERENCES AP_ANGAJATI(cod_angajat),
CONSTRAINT fk_cod_produs FOREIGN KEY(cod_produs) REFERENCES AP_PRODUSE(cod_produs));

ALTER TABLE AP_OFICII
Add CONSTRAINT fk_cod_manager FOREIGN KEY (cod_manager) REFERENCES AP_ANGAJATI(cod_angajat);

CREATE SEQUENCE produs_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;

