SET SERVEROUTPUT ON
DECLARE
    s VARCHAR2(50);
    d DATE;
    exc EXCEPTION;
    PRAGMA EXCEPTION_INIT(exc,-01858);
BEGIN
    s := '13-DEC-2004 6:56 PM';
    d := TO_DATE( s,'DD-MON-YYYY HH:MI:SS');
EXCEPTION
    WHEN exc THEN
    DBMS_OUTPUT.PUT_LINE('FORMAT INVALID!');
END;
/
