DROP TABLE GAM_OFICII CASCADE CONSTRAINTS;
CREATE TABLE GAM_OFICII
(
  COD_OFICIU VARCHAR2(2) PRIMARY KEY,
  LOCALITATE VARCHAR2(15),
  REGIUNE VARCHAR2(6),
  COD_MANAGER VARCHAR2(3)
);
DROP TABLE GAM_COMPANII CASCADE CONSTRAINTS;
CREATE TABLE GAM_COMPANII
(
  COD_COMPANIE VARCHAR2(2) PRIMARY KEY,
  COMPANIE VARCHAR2(15),
  REPREZENTANT_COMPANIE VARCHAR2(3),
  DATORIE NUMBER(8,2)
);

DROP TABLE GAM_ANGAJATI CASCADE CONSTRAINTS;
CREATE TABLE GAM_ANGAJATI
(
  COD_ANGAJAT VARCHAR2(2) PRIMARY KEY,
  NUME VARCHAR2(15),
  PRENUME VARCHAR2(15),
  VARSTA NUMBER(3),
  FUNCTIA VARCHAR2(20),
  COD_OFICIU VARCHAR2(2),
  DATA_ANGAJARE DATE,
  SUMA_PLANIFICATA NUMBER(8,2),
  CONSTRAINT FK_ANG_CODOF FOREIGN KEY(COD_OFICIU) REFERENCES GAM_OFICII(COD_OFICIU)
);

DROP TABLE GAM_PRODUSE CASCADE CONSTRAINTS;
CREATE TABLE GAM_PRODUSE
(
  COD_PRODUS NUMBER PRIMARY KEY,
  DESCRIERE VARCHAR2(50),
  PRET NUMBER(8,2),
  EXISTA VARCHAR2(1),
  CONSTRAINT CHK_PROD_EXISTA CHECK (EXISTA='Y' OR EXISTA='N')
);

DROP TABLE GAM_TRANZACTII CASCADE CONSTRAINTS;
CREATE TABLE GAM_TRANZACTII
(
  DATA_COMANDA DATE,
  COD_CLIENT VARCHAR2(2),
  COD_VANZATOR VARCHAR2(3),
  COD_PRODUS NUMBER,
  CANTITATE NUMBER,
  CONSTRAINT FK_TR_CODCLIENT FOREIGN KEY(COD_CLIENT) REFERENCES GAM_COMPANII(COD_COMPANIE),
  CONSTRAINT FK_TR_CODVANZATOR FOREIGN KEY(COD_VANZATOR) REFERENCES GAM_ANGAJATI(COD_ANGAJAT),
  CONSTRAINT FK_TR_CODPRODUS FOREIGN KEY(COD_PRODUS) REFERENCES GAM_PRODUSE(COD_PRODUS)
);

ALTER TABLE GAM_OFICII ADD CONSTRAINT FK_OF_CODMANAGER FOREIGN KEY(COD_MANAGER) REFERENCES GAM_ANGAJATI(COD_ANGAJAT);
ALTER TABLE GAM_COMPANII ADD CONSTRAINT FK_CO_REPRCOMP FOREIGN KEY(REPREZENTANT_COMPANIE) REFERENCES GAM_ANGAJATI(COD_ANGAJAT);

DROP SEQUENCE SEQ_CODPROD;
CREATE SEQUENCE SEQ_CODPROD
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
