CREATE OR REPLACE TRIGGER trg_PLF_trigger_create
AFTER INSERT ON PLF_CUSTOMERS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO PLF_credit_line (CUSTOMER_ID, CREDIT_LIMIT, CREATION_DATE, LAST_CHANGE_DATE, VALID_FROM, VALID_TO) 
	VALUES (:new.CUSTOMER_ID, 10000, to_date(SYSDATE,'DD.MM.YYYY'), to_date(SYSDATE,'DD.MM.YYYY'), to_date('01.01.2017','DD.MM.YYYY'), to_date('31.12.2020','DD.MM.YYYY'));
END;
/
