DROP TABLE LH_OFICII CASCADE CONSTRAINTS;
DROP TABLE LH_ANGAJATI CASCADE CONSTRAINTS;
DROP TABLE LH_COMPANII CASCADE CONSTRAINTS;
DROP TABLE LH_PRODUSE CASCADE CONSTRAINTS;
DROP TABLE LH_TRANZACTII CASCADE CONSTRAINTS;
DROP SEQUENCE CODPROD_SEQ;

CREATE TABLE LH_OFICII (COD_OFICIU VARCHAR2(2), 
LOCALITATE VARCHAR2(15), 
REGIUNEA VARCHAR2(6), 
COD_MANAGER VARCHAR2(3),
CONSTRAINT PK_CODOFICIU PRIMARY KEY (COD_OFICIU));

CREATE TABLE LH_ANGAJATI (COD_ANGAJAT VARCHAR2(2), 
NUME VARCHAR2(15), 
PRENUME VARCHAR2(15),
VARSTA NUMERIC, 
FUNCTIA VARCHAR2(20), 
COD_OFICIU VARCHAR2(2), 
DATA_ANGAJRII DATE,
SUMA_PLANIFICATE NUMERIC(*,2), 
CONSTRAINT PK_CODANGAJAT PRIMARY KEY(COD_ANGAJAT),
CONSTRAINT FK_ANGAJATIOFICII FOREIGN KEY (COD_OFICIU) REFERENCES LH_OFICII(COD_OFICIU));



ALTER TABLE LH_OFICII
ADD CONSTRAINT FK_OFICIIANGAJATI FOREIGN KEY (COD_MANAGER) REFERENCES LH_ANGAJATI(COD_ANGAJAT);

CREATE TABLE LH_COMPANII (COD_COMPANIE VARCHAR2(2), 
COMPANIA VARCHAR2(15), 
REPREZENTANT_COMPANIE VARCHAR2(3), 
DATORIA NUMBER(*,2), 
CONSTRAINT PK_CODCOMPANIE PRIMARY KEY (COD_COMPANIE),
CONSTRAINT FK_COMPANIEANGAJATI FOREIGN KEY (REPREZENTANT_COMPANIE) REFERENCES LH_ANGAJATI (COD_ANGAJAT));

CREATE TABLE LH_PRODUSE (COD_PRODUS NUMBER,
DESCRIERE VARCHAR2(30), 
PRET NUMBER(*,2), 
EXISTA VARCHAR2(1) 
CONSTRAINT CK_EXISTA CHECK (EXISTA='Y' OR EXISTA='N'), 
CONSTRAINT PK_CODPRODUS PRIMARY KEY(COD_PRODUS));

CREATE TABLE LH_TRANZACTII ( DATA_COMENZII DATE,
COD_CLIENT VARCHAR2(2), 
COD_VANZATOR VARCHAR2(3), 
COD_PRODUS NUMBER, 
CANTITATE NUMBER, 
CONSTRAINT FK_TRANZACTIICOMPANII FOREIGN KEY(COD_CLIENT) REFERENCES LH_COMPANII(COD_COMPANIE), 
CONSTRAINT FK_TRANZACTIIANGAJATI FOREIGN KEY(COD_VANZATOR) REFERENCES LH_ANGAJATI(COD_ANGAJAT), 
CONSTRAINT FK_TRANZACTIIPRODUSE FOREIGN KEY(COD_PRODUS) REFERENCES LH_PRODUSE(COD_PRODUS));



CREATE SEQUENCE CODPROD_SEQ
START WITH 1
INCREMENT BY 1 
MAXVALUE 5000
NOCYCLE
NOCACHE;
  

 
 




