DROP TABLE PLF_customers CASCADE CONSTRAINTS;
DROP TABLE PLF_credit_line CASCADE CONSTRAINTS;
DROP TRIGGER trg_PLF_trigger_create;

CREATE TABLE PLF_customers(
		CUSTOMER_ID Number(8),
		NAME Varchar(30),
CONSTRAINT PK_CID PRIMARY KEY (CUSTOMER_ID));

CREATE TABLE PLF_credit_line(
		CUSTOMER_ID Number (8),
		CREDIT_LIMIT Number (10,2) CHECK (CREDIT_LIMIT <> NULL AND CREDIT_LIMIT>0),
		CREATION_DATE Date NOT NULL,
		VALID_FROM Date NOT NULL,
		VALID_TO Date NOT NULL,
		LAST_CHANGE_DATE Date NOT NULL,
CONSTRAINT FK_CID FOREIGN KEY (CUSTOMER_ID)
REFERENCES PLF_customers(CUSTOMER_ID));
