--Afiseaza media salariului grupat pe departamente si functie.
SELECT DEPARTMENT_ID, 
       JOB_ID,
       ROUND(AVG(SALARY)) SALARIUL_MEDIU
FROM   EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID, JOB_ID; 

--Afiseaza din tabela tranzactii, codul clientului, al produsului si data comenzii. 
--Un client poate avea mai multe comenzi. 
--Afisati si cel mai recent produs comandat de fiecare client in parte. 
SELECT * 
FROM (SELECT T.COD_CLIENT,
             T.COD_PRODUS,
             P.DESCRIERE PRODUS_COMANDAT,
             T.DATA_COMANDA DATA_ULTIMA_COMANDA,
             ROW_NUMBER() OVER(PARTITION BY T.COD_CLIENT ORDER BY T.DATA_COMANDA DESC) RN
      FROM GAM_TRANZACTII T, GAM_PRODUSE P
      WHERE T.COD_PRODUS = P.COD_PRODUS
      ORDER BY COD_CLIENT)
WHERE RN=1;

--solutia 2 folosind FIRST_VALUE
SELECT DISTINCT T.COD_CLIENT,
       FIRST_VALUE(T.COD_PRODUS)
            OVER (PARTITION BY COD_CLIENT ORDER BY DATA_COMANDA DESC
            RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) COD_PRODUS,
       FIRST_VALUE(DESCRIERE)
            OVER (PARTITION BY COD_CLIENT ORDER BY DATA_COMANDA DESC
            RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) PRODUS_COMANDAT,
       FIRST_VALUE(DATA_COMANDA)
            OVER (PARTITION BY COD_CLIENT ORDER BY DATA_COMANDA DESC
            RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) DATA_ULTIMA_COMANDA
FROM GAM_TRANZACTII T, GAM_PRODUSE P
WHERE T.COD_PRODUS = P.COD_PRODUS
ORDER BY COD_CLIENT;

--solutia 3
SELECT *
FROM
    (SELECT t.COD_CLIENT,
			      t.COD_PRODUS,
            p.DESCRIERE produs_comandat,
			      t.DATA_COMANDA ,
		      	FIRST_VALUE(t.DATA_COMANDA) OVER(PARTITION BY t.COD_CLIENT ORDER BY t.DATA_COMANDA DESC) DATA_ULTIMA_COMANDA ,
			      FIRST_VALUE(t.COD_PRODUS) OVER(PARTITION BY t.COD_CLIENT ORDER BY t.DATA_COMANDA DESC) ULTIMUL_PRODUS
	    FROM  GAM_TRANZACTII t,
            GAM_PRODUSE p
	    WHERE t.COD_PRODUS = p.COD_PRODUS) tr
WHERE tr.ULTIMUL_PRODUS      = tr.COD_PRODUS
AND   tr.DATA_ULTIMA_COMANDA = tr.DATA_COMANDA;