INSERT INTO AP_OFICII VALUES('BL','Beltsy','nord',NULL);
INSERT INTO AP_OFICII VALUES('C','Kishinew','centru',NULL);
INSERT INTO AP_OFICII VALUES('CH','Cahul','sud',NULL);
INSERT INTO AP_OFICII VALUES('ED','Edinets','nord',NULL);
INSERT INTO AP_OFICII VALUES('GL','Glodeni','nord',NULL);
INSERT INTO AP_OFICII VALUES('OR','Orhei','centry',NULL);
INSERT INTO AP_OFICII VALUES('RZ','Rezina','nord',NULL);
INSERT INTO AP_OFICII VALUES('SR','Soroca','nord',NULL);
INSERT INTO AP_OFICII VALUES('UN','Ungheni','centru',NULL);

INSERT INTO AP_ANGAJATI VALUES('BC','Bucataru','Constantin',31,'contabil','SR',
TO_DATE('18.01.2001','dd.MM.yyyy'),0);
INSERT INTO AP_ANGAJATI VALUES('BN','Bucur','Nicolae',27,'manager','SR',
TO_DATE('31.01.2001','dd.MM.yyyy'),28000);
INSERT INTO AP_ANGAJATI VALUES('CI','Cozma','Ion',20,'reprezentant','OR',
TO_DATE('17.11.2001','dd.MM.yyyy'),2000);
INSERT INTO AP_ANGAJATI VALUES('DE','Dodon','Elena',34,'contabil','ED',
TO_DATE('20.02.2000','dd.MM.yyyy'),0);
INSERT INTO AP_ANGAJATI VALUES('DR','Dutca','Radion',33,'reprezentant','GL',
TO_DATE('12.12.1999','dd.MM.yyyy'),3250);
INSERT INTO AP_ANGAJATI VALUES('FE','Frumosu','Elena',37,'contabil','ED',
TO_DATE('12.02.1998','dd.MM.yyyy'),0);
INSERT INTO AP_ANGAJATI VALUES('FN','Florea','Nicoleta',23,'reprezentant','BL',
TO_DATE('13.06.2000','dd.MM.yyyy'),2500);
INSERT INTO AP_ANGAJATI VALUES('GC','Grosu','Corina',19,'reprezentant','RZ',
TO_DATE('04.04.2000','dd.MM.yyyy'),1900);
INSERT INTO AP_ANGAJATI VALUES('GI','Gomoja','Ilie',32,'reprezentant','CH',
TO_DATE('13.07.2005','dd.MM.yyyy'),3250);
INSERT INTO AP_ANGAJATI VALUES('GL','Grosu','Leonid',23,'reprezentant','ED',
TO_DATE('28.03.2000','dd.MM.yyyy'),2500);
INSERT INTO AP_ANGAJATI VALUES('GM','Grosu','Mihai',42,'sef','C',
TO_DATE('07.02.1998','dd.MM.yyyy'),0);
INSERT INTO AP_ANGAJATI VALUES('GT','Graur','Teodor',35,'reprezentant','SR',
TO_DATE('18.08.2004','dd.MM.yyyy'),3500);
INSERT INTO AP_ANGAJATI VALUES('HI','Harea','Igor',25,'manager','CH',
TO_DATE('30.03.2003','dd.MM.yyyy'),22000);
INSERT INTO AP_ANGAJATI VALUES('LA','Lungu','Alexandru',43,'sef adjunc','C',
TO_DATE('07.02.1998','dd.MM.yyyy'),0);
INSERT INTO AP_ANGAJATI VALUES('LV','Lisnic','Vladimir',29,'manager','OR',
TO_DATE('13.09.2001','dd.MM.yyyy'),351);
INSERT INTO AP_ANGAJATI VALUES('ML','Mutu','Livia',38,'manager','BL',
TO_DATE('09.02.1999','dd.MM.yyyy'),15000);
INSERT INTO AP_ANGAJATI VALUES('MS','Mutu','Sorina',35,'reprezentant','UN',
TO_DATE('06.04.2004','dd.MM.yyyy'),3500);
INSERT INTO AP_ANGAJATI VALUES('NV','Nanu','Vasile',45,'reprezentant','C',
TO_DATE('09.02.1998','dd.MM.yyyy'),4500);
INSERT INTO AP_ANGAJATI VALUES('PI','Prisacaru','Inga',27,'reprezentant','UN',
TO_DATE('18.03.2001','dd.MM.yyyy'),2750);
INSERT INTO AP_ANGAJATI VALUES('RD','Rusu','Dorina',35,'reprezentant','OR',
TO_DATE('18.09.2001','dd.MM.yyyy'),3500);
INSERT INTO AP_ANGAJATI VALUES('SA','Speriatu','Ana',31,'contabil','GL',
TO_DATE('15.01.2003','dd.MM.yyyy'),0);
INSERT INTO AP_ANGAJATI VALUES('SD','Spada','Doru',29,'manager','RZ',
TO_DATE('12.01.2003','dd.MM.yyyy'),1800);
INSERT INTO AP_ANGAJATI VALUES('SM','Surdu','Mihaiela',25,'reprezentant','BL',
TO_DATE('12.03.2000','dd.MM.yyyy'),20000);
INSERT INTO AP_ANGAJATI VALUES('VD','Vieru','Dorin',32,'manager','C',
TO_DATE('08.02.1998','dd.MM.yyyy'),80000);
INSERT INTO AP_ANGAJATI VALUES('VI','Vrabie','Ion',42,'contabil','RZ',
TO_DATE('18.10.2002','dd.MM.yyyy'),0);

INSERT INTO AP_COMPANII VALUES ('AL','Auto Lada','NV',7500);
INSERT INTO AP_COMPANII VALUES ('AS','Asito','PI',26000);
INSERT INTO AP_COMPANII VALUES ('AT','Astra','PI',14780);
INSERT INTO AP_COMPANII VALUES ('AV','Avon','GC',12000);
INSERT INTO AP_COMPANII VALUES ('BA','Basarabia','GC',0);
INSERT INTO AP_COMPANII VALUES ('BI','Bizpro','PI',13050);
INSERT INTO AP_COMPANII VALUES ('CA','Cascad','GI',12300);
INSERT INTO AP_COMPANII VALUES ('FB','Floribel','GL',600);
INSERT INTO AP_COMPANII VALUES ('FL','Floarea','GL',0);
INSERT INTO AP_COMPANII VALUES ('IL','InLac','GI',1000);
INSERT INTO AP_COMPANII VALUES ('KN','Knauf','PI',0);
INSERT INTO AP_COMPANII VALUES ('LO','Luck Oil','NV',13000);
INSERT INTO AP_COMPANII VALUES ('PA','Patria','DR',500);
INSERT INTO AP_COMPANII VALUES ('PE','Petrom','NV',50000);
INSERT INTO AP_COMPANII VALUES ('TC','TransCom','MS',6000);
INSERT INTO AP_COMPANII VALUES ('TI','Tirex','NV',5000);
INSERT INTO AP_COMPANII VALUES ('TU','Tutun Ind','GL',1000);
INSERT INTO AP_COMPANII VALUES ('VT','Vitanta','GI',800);
INSERT INTO AP_COMPANII VALUES ('ZO','Zorile','GT',22890);

INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Monitor LG 17"',100.00,'Y');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Monitor Samsung 15"',50.00,'N');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Televizor JVS 54cm"',280.00,'N');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Procesor Pentium 4',130.00,'Y');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Procesor Celeron 2000',125.00,'Y');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Mouse Genius optic',4.00,'N');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Mouse Logitech optic',5.00,'Y');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Televizor Sony 72cm',485.00,'N');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'DVD Sony 50',75.00,'N');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'DVD Sony 32-16-32',135,'Y');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'CD-R Benq 700MB',0.10,'Y');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'CD-Rw Benq 700MB',0.25,'Y');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Tastiera Logitech alba',6.75,'Y');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Tastiera Logitech neagra',9.75,'N');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Monitor Samsung 17"',85.50,'Y');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Monitor Samsung 21"',109.50,'N');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Monitor Samtron 15"',35.50,'N');
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Televizor Alfa 51cm',100.40,'Y'); 
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Televizor Polar 54cm',200.00,'N'); 
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Filtru Sven 220V',3.75,'Y'); 
INSERT INTO AP_PRODUSE VALUES(produs_seq.NEXTVAL,'Telefon Siemens A55',200.00,'Y');

INSERT INTO AP_TRANZACTII VALUES(TO_DATE('01.01.2005','dd.MM.yyyy'),'BI','NV',7,5);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('01.01.2005','dd.MM.yyyy'),'IL','PI',15,4);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('03.01.2005','dd.MM.yyyy'),'VT','HI',14,12);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('03.01.2005','dd.MM.yyyy'),'ZO','GI',12,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('14.01.2005','dd.MM.yyyy'),'VT','BN',15,8);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('18.01.2005','dd.MM.yyyy'),'TI','GL',12,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('31.01.2005','dd.MM.yyyy'),'CA','GI',11,2);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('31.01.2005','dd.MM.yyyy'),'VT','BN',14,9);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('02.02.2005','dd.MM.yyyy'),'PE','SM',12,2);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('11.02.2005','dd.MM.yyyy'),'LO','SM',2,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('11.02.2005','dd.MM.yyyy'),'TI','FN',21,2);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('22.02.2005','dd.MM.yyyy'),'TI','NV',13,2);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('02.03.2005','dd.MM.yyyy'),'AL','LV',17,2);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('03.03.2005','dd.MM.yyyy'),'FL','PI',11,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('04.03.2005','dd.MM.yyyy'),'TI','SD',14,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('12.03.2005','dd.MM.yyyy'),'FL','PI',8,1);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('12.03.2005','dd.MM.yyyy'),'VT','GI',14,4);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('26.03.2005','dd.MM.yyyy'),'AS','GC',8,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('26.03.2005','dd.MM.yyyy'),'PA','SD',12,10);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('04.04.2005','dd.MM.yyyy'),'AT','DR',11,5);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('14.04.2005','dd.MM.yyyy'),'FL','SM',13,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('18.04.2005','dd.MM.yyyy'),'AS','LV',3,1);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('18.04.2005','dd.MM.yyyy'),'PE','BC',18,8);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('18.04.2005','dd.MM.yyyy'),'TC','ML',20,2);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('01.05.2005','dd.MM.yyyy'),'ZO','BN',21,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('24.05.2005','dd.MM.yyyy'),'AT','FN',3,10);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('24.05.2005','dd.MM.yyyy'),'AV','CI',19,2);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('13.06.2005','dd.MM.yyyy'),'AT','GC',9,2);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('13.06.2005','dd.MM.yyyy'),'PA','HI',13,11);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('16.06.2005','dd.MM.yyyy'),'FB','PI',16,8);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('04.07.2005','dd.MM.yyyy'),'ZO','HI',11,5);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('11.07.2005','dd.MM.yyyy'),'TI','PI',15,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('16.07.2005','dd.MM.yyyy'),'FB','RD',18,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('16.07.2005','dd.MM.yyyy'),'ZO','ML',4,11);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('08.08.2005','dd.MM.yyyy'),'LO','DR',5,9);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('08.08.2005','dd.MM.yyyy'),'PA','GC',11,4);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('16.08.2005','dd.MM.yyyy'),'CA','CI',5,12);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('16.08.2005','dd.MM.yyyy'),'VT','NV',17,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('20.09.2005','dd.MM.yyyy'),'KN','RD',6,2);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('20.09.2005','dd.MM.yyyy'),'PA','NV',16,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('10.10.2005','dd.MM.yyyy'),'AT','MS',11,5);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('10.10.2005','dd.MM.yyyy'),'VT','MS',20,7);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('11.11.2005','dd.MM.yyyy'),'PE','SD',19,6);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('12.11.2005','dd.MM.yyyy'),'PA','DR',12,4);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('12.11.2005','dd.MM.yyyy'),'PE','BN',4,3);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('19.11.2005','dd.MM.yyyy'),'CA','PI',17,8);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('12.12.2005','dd.MM.yyyy'),'IL','GL',13,4);
INSERT INTO AP_TRANZACTII VALUES(TO_DATE('12.12.2005','dd.MM.yyyy'),'TI','GI',3,2);

UPDATE AP_OFICII SET cod_manager='ML' WHERE UPPER(cod_oficiu)='BL';
UPDATE AP_OFICII SET cod_manager='VD' WHERE UPPER(cod_oficiu)='C';
UPDATE AP_OFICII SET cod_manager='HI' WHERE UPPER(cod_oficiu)='CH';
UPDATE AP_OFICII SET cod_manager='ML' WHERE UPPER(cod_oficiu)='ED';
UPDATE AP_OFICII SET cod_manager='ML' WHERE UPPER(cod_oficiu)='GL';
UPDATE AP_OFICII SET cod_manager='LV' WHERE UPPER(cod_oficiu)='OR';
UPDATE AP_OFICII SET cod_manager='SD' WHERE UPPER(cod_oficiu)='RZ';
UPDATE AP_OFICII SET cod_manager='BN' WHERE UPPER(cod_oficiu)='SR';
UPDATE AP_OFICII SET cod_manager='VD' WHERE UPPER(cod_oficiu)='UN';

COMMIT;

