--SUMA A DOUA NUMERE IMPARTITA LA 3. NUMERELE SE CITESC DE LA TASTATURA
SET SERVEROUTPUT ON
ACCEPT P_NUMBER1 PROMPT 'INTRODUCETI PRIMUL NUMAR: '
ACCEPT P_NUMBER2 PROMPT 'INTRODUCETI AL DOILEA NUMAR: '
DECLARE
    G_REZULTAT NUMBER;
    V_NUM1 NUMBER(9,2) := &P_NUMBER1;
    V_NUM2 NUMBER(9,2) := &P_NUMBER2;
BEGIN
    G_REZULTAT := V_NUM1+V_NUM2;
    DBMS_OUTPUT.PUT_LINE('Suma dintre '||v_num1||' si '||v_num2||' este: '||G_REZULTAT);
    G_REZULTAT := G_REZULTAT/3;
    DBMS_OUTPUT.PUT_LINE('Rezultatul impartirii sumei la 3 este: '||G_REZULTAT);
END;